owner: isar-labs
repo: status

sites:
  - name: Suite
    url: https://suite.isar-labs.com
    maxResponseTime: 8000
  - name: Construction Documentation
    url: https://construction-documentation.isar-labs.com
    maxResponseTime: 8000
  - name: Document Workflow
    url: https://document-workflow.isar-labs.com
    maxResponseTime: 8000
  - name: Vercel CDN & Serverless (third party)
    url: https://www.vercel-status.com/api/v2/summary.json
    __dangerous__body_down_if_text_missing: '"indicator":"none"'
    __dangerous__body_degraded: '"indicator":"minor"'
    __dangerous__body_down: '"status":"major_outage"'
    __dangerous__body_down_if_text_missing_2: '"name":"Serverless Functions","status":"operational"'
    __dangerous__body_down_if_text_missing_3: '"name":"Edge Network","status":"operational"'
    maxResponseTime: 10000
  - name: Trigger.dev (third party)
    url: https://status.trigger.dev
    __dangerous__body_down_if_text_missing: "All services are online"
    maxResponseTime: 15000
  - name: Cloudflare (third party)
    url: https://www.cloudflarestatus.com/api/v2/summary.json
    __dangerous__body_down: '"indicator":"critical"'
    __dangerous__body_degraded: '"indicator":"major"'
    maxResponseTime: 12000
  - name: Neon DB (third party)
    url: https://neonstatus.com
    __dangerous__body_down_if_text_missing: "All Systems Operational"
    __dangerous__body_degraded: "Partial Service Disruption"
    __dangerous__body_down: "Service Disruption"
    expectedStatusCodes:
      - 200
    maxResponseTime: 15000

assignees: # Users to assign downtime issues (optional)
  - alexanderhodes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isar-labs.com
  #baseUrl: /upptime-demo
  favicon: https://status.isar-labs.com/icon.png
  logoUrl: https://status.isar-labs.com/icon.png
  name: Status
  theme: light
  introTitle: "Das ist die Status-Seite von **Isar Labs**."
  introMessage: "Hier findest du den aktuellen Status unserer Dienste. Wir arbeiten kontinuierlich daran, eine hohe Verfügbarkeit und Zuverlässigkeit zu gewährleisten."
  navbar:
    - title: Website
      href: https://isar-labs.com
    - title: Suite
      href: https://suite.isar-labs.com
  js: "const format = new Intl.NumberFormat('de-DE'); function formatText(element) {   const text = element.textContent;   if (text.includes('ms') && !text.includes('.')) {     const responseTime = text.replace('ms', '').trim();     const time = parseInt(responseTime, 10);     if (!isNaN(time)) {       element.textContent = format.format(time) + ' ' + 'ms';     }   } } function formatNumbers() {   const dataElements = document.getElementsByClassName('data');   for (let i = 0; i < dataElements.length; i++) {     formatText(dataElements[i]);   }   const elements = document.getElementsByTagName('dd');   for (let i = 0; i < elements.length; i++) {     formatText(elements[i]);   } } function replaceIncidentTexts() {   const elements = document.querySelectorAll('section article h4');   elements.forEach((element) => {     if (element.textContent.indexOf('is down') !== -1) {       element.textContent = element.textContent.replace(         'is down',         'ist ausgefallen'       );     } else if (element.textContent.indexOf('has degraded performance') !== -1) {       element.textContent = element.textContent.replace(         'has degraded performance',         'hat eine verminderte Leistung'       );     }   }); } if (document.readyState === 'loading') {   document.addEventListener('DOMContentLoaded', formatNumbers);   document.addEventListener('DOMContentLoaded', replaceIncidentTexts); } else {   formatNumbers();   replaceIncidentTexts(); } setTimeout(formatNumbers, 500); setTimeout(replaceIncidentTexts, 500);"

i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme funktionsfähig
  incidentReport: "Vorfall #$NUMBER Bericht →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: "Vorfall #$NUMBER Details"
  incidentDetails: Vorfall Details
  incidentFixed: Behoben
  incidentFixedSummary: Geschlossen am $DATE mit $POSTS Beiträgen
  incidentMonitoring: Überwachung
  incidentMonitoringSummary: Überwachung gestartet am $DATE mit $POSTS Beiträgen
  incidentPageTitle: Vorfall Status
  footer: Diese Seite ist [Open Source]($REPO), powered by [Upptime](https://upptime.js.org)
  liveStatus: Live Status
  overallUptime: "Gesamtverfügbarkeit: $UPTIME"
  overallUptimeTitle: Gesamtverfügbarkeit
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7-Tage Antwortzeit
  up: Aktiv
  down: Inaktiv
  degraded: Beeinträchtigt
  ms: ms
  loading: Laden...
  navGitHub: GitHub
  rateLimitExceededTitle: Rate Limit überschritten
  rateLimitExceededIntro: Du hast die Anzahl der Anfragen überschritten
  rateLimitExceededWhatDoesThisMean: Was bedeutet das?
  rateLimitExceededErrorHowCanFix: Wie kann ich das beheben?
  rateLimitExceededErrorHowCanFixIntro: Wenn du ein Mensch bist, dann bedeutet das
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: Beim Abrufen der neuesten Status-Details ist ein Fehler aufgetreten.
  errorText: Du kannst es in wenigen Momenten erneut versuchen.
  errorHome: Zurück zur Startseite
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Behoben in $MINUTES Minuten mit $POSTS Beiträgen
  liveStatusHtmlComment: "<!--\nDiese Seite ist Open Source! Du kannst helfen, sie zu verbessern.\nhttps://github.com/isar-labs/status\n-->"
  numFormatterThousands: "."
  numFormatterMillions: ","
  locale: de-DE
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"  
