owner: isar-labs
repo: status

sites:
  - name: Suite
    url: https://suite.isar-labs.com
    maxResponseTime: 8000
  - name: Construction Documentation
    url: https://construction-documentation.isar-labs.com
    maxResponseTime: 8000
  - name: Document Workflow
    url: https://document-workflow.isar-labs.com
    maxResponseTime: 8000
  - name: Vercel CDN & Serverless (third party)
    url: https://www.vercel-status.com/api/v2/summary.json
    __dangerous__body_down_if_text_missing: '"indicator":"none"'
    __dangerous__body_degraded: '"indicator":"minor"'
    __dangerous__body_down: '"status":"major_outage"'
    __dangerous__body_down_if_text_missing_2: '"name":"Serverless Functions","status":"operational"'
    __dangerous__body_down_if_text_missing_3: '"name":"Edge Network","status":"operational"'
    maxResponseTime: 10000
  - name: Trigger.dev (third party)
    url: https://status.trigger.dev
    __dangerous__body_down_if_text_missing: "All services are online"
    maxResponseTime: 15000
  - name: Neon Database (third party)
    url: https://neonstatus.com/aws-europe-frankfurt
    __dangerous__body_down: "major outage"
    __dangerous__body_degraded: "degraded performance"
    expectedStatusCodes:
      - 200
    maxResponseTime: 15000

assignees: # Users to assign downtime issues (optional)
  - alexanderhodes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isar-labs.com
  #baseUrl: /upptime-demo
  favicon: https://raw.githubusercontent.com/isar-labs/status/refs/heads/master/assets/icon.png
  logoUrl: https://raw.githubusercontent.com/isar-labs/status/refs/heads/master/assets/icon.png
  name: Status
  theme: light
  introTitle: "Das ist die Status-Seite von **Isar Labs**."
  introMessage: "Hier findest du den aktuellen Status unserer Dienste. Wir arbeiten kontinuierlich daran, eine hohe Verfügbarkeit und Zuverlässigkeit zu gewährleisten."
  navbar:
    - title: Website
      href: https://isar-labs.com
    - title: Suite
      href: https://suite.isar-labs.com
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"  
